model_type: "regression"
model_data: "data/input/regression/regression_dummy_data.csv"
independent_variables: ['0','1','2','3','4','5','6','7','8','9','10','11','12']
dependent_variable: 'target'
models_to_run: {
  "random_forest_regressor": {
    'n_estimators': [50, 100, 150],
    'max_depth': [ 10, 20, 30], # None
    #'min_samples_split': [2, 5, 10],
    #'min_samples_leaf': [1, 2, 4],
    #'max_features': ['auto', 'sqrt', 'log2'],
    #'bootstrap': [True, False]
},
"support_vector_regressor": {
  'C': [0.1, 1, 10],
  'epsilon': [0.01, 0.1, 0.2],
  'kernel': ['linear', 'rbf', 'poly']
}

}
train_test_split: { 
  test_size: 0.2 

}
num_folds: 10 