model_type: "classification"
model_data: "data/input/classification/classification_dummy_data.csv"
artifact_path: "/home/avijit/selflearning/auto_ml/avi_auto_ml/data/output/classification/"
independent_variables: ['0','1']
dependent_variable: 'target'
number_of_classes: 3
num_folds: 10
models_to_run: {
  'random_forest': {
    'n_estimators': [50, 100, 150],
    'max_depth': [ 10, 20, 30], # None
    #'min_samples_split': [2, 5, 10],
    #'min_samples_leaf': [1, 2, 4],
    #'max_features': ['auto', 'sqrt', 'log2'],
    #'bootstrap': [True, False]
},
'svm': {
  'C': [1,2,3, 0.75],
  'kernel': ['linear', 'poly', 'rbf', 'sigmoid',] # 'precomputed'
}

}
train_test_split: { 
  test_size: 0.2 

} 
